No protocol specified
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[lavoisier:289765] *** Process received signal ***
[lavoisier:289765] Signal: Aborted (6)
[lavoisier:289765] Signal code:  (-6)
[lavoisier:289765] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7fe51c545090]
[lavoisier:289765] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fe51c54500b]
[lavoisier:289765] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7fe51c524859]
[lavoisier:289765] [ 3] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa4ee6)[0x7fe51c90eee6]
[lavoisier:289765] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6f8c)[0x7fe51c920f8c]
[lavoisier:289765] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6ff7)[0x7fe51c920ff7]
[lavoisier:289765] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xb7258)[0x7fe51c921258]
[lavoisier:289765] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa82a7)[0x7fe51c9122a7]
[lavoisier:289765] [ 8] nnp-train(+0x63591)[0x5591c8f8a591]
[lavoisier:289765] [ 9] nnp-train(+0x723b6)[0x5591c8f993b6]
[lavoisier:289765] [10] nnp-train(+0x29b03)[0x5591c8f50b03]
[lavoisier:289765] [11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fe51c526083]
[lavoisier:289765] [12] nnp-train(+0x2ac5e)[0x5591c8f51c5e]
[lavoisier:289765] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 11 with PID 0 on node lavoisier exited on signal 6 (Aborted).
--------------------------------------------------------------------------
